// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunVale(arg1) {
  return window['go']['main']['App']['RunVale'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
