// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1:string):Promise<string>;

export function RunVale(arg1:string):Promise<string>;

export function Search(arg1:string):Promise<string>;
